project:
  type: website
  output-dir: _site

website:
  title: "Spaceflights"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: flatly
    #  - resources/theme.scss
    mainfont: "Atkinson Hyperlegible"
    linestretch: 1.5
    fontsize: 1.2em
    toc: true
    toc-depth: 2
    number-sections: true
    number-depth: 2

bibliography: resources/spaceflights.bib
csl: resources/ieee.csl
nocite: "@*"

execute:
  echo: false
  warning: false
  message: false
  error: true
  eval: true
  cache: false
