# .github/workflows/docker-build-push.yml
name: Docker Build and Push CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set owner to lowercase
        id: owner_case
        run: echo "OWNER_LC=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }} # This can remain as github.actor for login
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ env.OWNER_LC }}/spaceflights-app

      - name: Build and push Docker image to GHCR
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Output Pushed Image Digest
        run: |
          echo "Pushed image digest: ${{ steps.build-and-push.outputs.digest }}"

      - name: Run Kedro pipeline from Docker image
        if: success()
        run: |
          echo "" # Add a blank line for spacing before
          echo "************************************************************************************"
          echo "***************** STARTING KEDRO PIPELINE EXECUTION   ***************************"
          echo "************************************************************************************"
          echo "Running Kedro pipeline from image: ghcr.io/${{ env.OWNER_LC }}/spaceflights-app:${{ github.ref_name }}"
          
          docker run --rm ghcr.io/${{ env.OWNER_LC }}/spaceflights-app:${{ github.ref_name }}
          
          echo "" # Add a blank line for spacing after
          echo "************************************************************************************"
          echo "***************** KEDRO PIPELINE EXECUTION FINISHED    ***************************"
          echo "************************************************************************************"
          echo ""

